fastify printRoutes and close with promise
in fastify-cli v2.2.0 invoke printRoutes(args).close() cause error
`TypeError: printRoutes(...).close is not a function`